build:
    environment:
        php:
            version: 7.1             
    tests:
        before:
            - 'composer install --dev --prefer-source'
            - cp app/config/parameters.yml.dist app/config/parameters.yml
            - php bin/console doctrine:database:create --env=test
            - php bin/console doctrine:migration:migrate --no-interaction --env=test
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover-file'
                coverage:
                    file: 'clover-file'
                    format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths: [vendor/*, var/*,  app/*, bin/*, tests/*, web/*]
before_commands:
    - 'composer install --dev --prefer-source'
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:migration:migrate --no-interaction --env=test
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, var, app, bin, tests, web]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, var, app, bin, tests, web]
